### PR TITLE
Unreachable strategy, kill selection, port mappings labels and fix to upgrade strategy

### PR DESCRIPTION
**Pull request by kamsz**
Hi,

This PR adds unreachable strategy and kill selections fields (https://github.com/gambol99/go-marathon/pull/280). It also fixes broken upgrade strategy.

I've never worked with vendor before, so if I've broken something, let me know and I'll fix it.

### CODE REVIEW

**Comment by nicgrayson** [comment]
@kamsz please add tests for these new fields

**Comment by luisdavim** [comment]
I know tests are important but can't we have this merged and workout the tests latter if @kamsz doesn't respond?

**Comment by kamsz** [comment]
@nicgrayson Added tests.

**Comment by kamsz** [comment]
Added labels to port mappings that allow specifying VIPs.

**Comment by luisdavim** [comment]
Thanks a million @kamsz !! @nicgrayson do you think you can get this merged now?

**Comment by ngrayson-amfam** [comment]
LGTM

**Pull request merged**
